# Generated by Django 3.1.2 on 2020-11-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('manufacture', models.CharField(choices=[('AB', 'Airbus'), ('BN', 'Boeing'), ('LM', 'Lockheed Martin')], max_length=55)),
                ('role', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True)),
                ('produced', models.DateField()),
                ('description', models.TextField(max_length=5000)),
                ('status', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('family', models.CharField(max_length=30)),
                ('first_flight', models.DateField()),
            ],
        ),
    ]
