# Generated by Django 3.1.2 on 2020-11-02 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftSpecs',
            fields=[
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='aircraft.aircraft')),
                ('range', models.IntegerField()),
                ('seating', models.IntegerField(blank=True, verbose_name='Seating')),
                ('replaces_current_model', models.CharField(blank=True, max_length=30)),
                ('competes_against', models.CharField(blank=True, max_length=30)),
                ('length', models.IntegerField(blank=True, verbose_name='Length')),
                ('wing_span', models.IntegerField(blank=True, verbose_name='Wing_span')),
                ('height', models.IntegerField(blank=True, verbose_name='Height')),
                ('fuselage_width_ext', models.IntegerField(blank=True, verbose_name='Fuselage width exterior')),
                ('cabin_width_Int', models.IntegerField(blank=True, verbose_name='Cabin width interior')),
                ('track', models.IntegerField(blank=True, verbose_name='Track')),
                ('wheelbase', models.IntegerField(blank=True, verbose_name='wheelbase')),
                ('maximum_operating_speed', models.IntegerField(blank=True, verbose_name='Maximum operating speed')),
                ('maximum_ramp_weight', models.IntegerField(blank=True, verbose_name='Maximum ramp weight')),
                ('maximum_take_off_weight', models.IntegerField(blank=True, verbose_name='Maximum take off weight')),
                ('maximum_landing_weight', models.IntegerField(blank=True, verbose_name='Maximum landing weight')),
                ('maximum_zero_fuel_weight', models.IntegerField(blank=True, verbose_name='Maximum zero fuel weight')),
                ('maximum_fuel_capacity', models.IntegerField(blank=True, verbose_name='Maximum fuel capacity')),
                ('engines', models.CharField(blank=True, choices=[('RRTrentXWB337kN (74,000 LBF)', 'RR Trent XWB 337kN (74,000 LBF)'), ('RRTrentXWB374kN (83,000 LBF)', 'RR Trent XWB 374kN (83,000 LBF)'), ('RRTrentXWB432kN (97,000 LBF)', 'RR Trent XWB 432kN (97,000 LBF)')], max_length=55)),
                ('average_unit_price', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='first_flight',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='produced',
        ),
        migrations.AddField(
            model_name='aircraft',
            name='featured_photo',
            field=models.ImageField(blank=True, upload_to='photos/airplanes/featured/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='is_featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='photo1',
            field=models.ImageField(blank=True, upload_to='photos/airplanes/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='photo2',
            field=models.ImageField(blank=True, upload_to='photos/airplanes/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='photo3',
            field=models.ImageField(blank=True, upload_to='photos/airplanes/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='photo4',
            field=models.ImageField(blank=True, upload_to='photos/airplanes/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='poststatus',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='role',
            field=models.CharField(choices=[('NBRP', 'Narrow-body Regional jet airplane'), ('XWB', 'Extrawide-body jet airplane')], max_length=100),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='status',
            field=models.CharField(choices=[('LTD', 'Limited to freighters and executive use[a]'), ('INS', 'In service')], max_length=30),
        ),
    ]
