# Generated by Django 3.1.2 on 2020-11-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0002_auto_20201102_1337'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AircraftSpecs',
            new_name='AircraftSpec',
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
