# Generated by Django 3.1.2 on 2020-11-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0003_auto_20201102_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraftspec',
            name='cabin_width_Int',
            field=models.FloatField(blank=True, verbose_name='Cabin width interior'),
        ),
        migrations.AlterField(
            model_name='aircraftspec',
            name='fuselage_width_ext',
            field=models.FloatField(blank=True, verbose_name='Fuselage width exterior'),
        ),
        migrations.AlterField(
            model_name='aircraftspec',
            name='height',
            field=models.FloatField(blank=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='aircraftspec',
            name='length',
            field=models.FloatField(blank=True, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='aircraftspec',
            name='maximum_fuel_capacity',
            field=models.FloatField(blank=True, verbose_name='Maximum fuel capacity'),
        ),
        migrations.AlterField(
            model_name='aircraftspec',
            name='maximum_landing_weight',
            field=models.FloatField(blank=True, verbose_name='Maximum landing weight'),
        ),
        migrations.AlterField(
            model_name='aircraftspec',
            name='maximum_operating_speed',
            field=models.FloatField(blank=True, verbose_name='Maximum operating speed'),
        ),
        migrations.AlterField(
            model_name='aircraftspec',
            name='maximum_ramp_weight',
            field=models.FloatField(blank=True, verbose_name='Maximum ramp weight'),
        ),
        migrations.AlterField(
            model_name='aircraftspec',
            name='maximum_take_off_weight',
            field=models.FloatField(blank=True, verbose_name='Maximum take off weight'),
        ),
        migrations.AlterField(
            model_name='aircraftspec',
            name='maximum_zero_fuel_weight',
            field=models.FloatField(blank=True, verbose_name='Maximum zero fuel weight'),
        ),
        migrations.AlterField(
            model_name='aircraftspec',
            name='range',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='aircraftspec',
            name='track',
            field=models.FloatField(blank=True, verbose_name='Track'),
        ),
        migrations.AlterField(
            model_name='aircraftspec',
            name='wheelbase',
            field=models.FloatField(blank=True, verbose_name='wheelbase'),
        ),
        migrations.AlterField(
            model_name='aircraftspec',
            name='wing_span',
            field=models.FloatField(blank=True, verbose_name='Wing_span'),
        ),
    ]
