# Generated by Django 3.1.2 on 2020-11-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0004_auto_20201102_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='manufacture',
            field=models.CharField(choices=[('Airbus', 'Airbus'), ('Boeing', 'Boeing'), ('Lockheed Martin', 'Lockheed Martin')], max_length=55),
        ),
    ]
