# Generated by Django 3.1.2 on 2020-11-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0006_auto_20201102_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraftspec',
            name='average_unit_price',
        ),
        migrations.RemoveField(
            model_name='aircraftspec',
            name='cabin_width_Int',
        ),
        migrations.RemoveField(
            model_name='aircraftspec',
            name='competes_against',
        ),
        migrations.RemoveField(
            model_name='aircraftspec',
            name='engines',
        ),
        migrations.RemoveField(
            model_name='aircraftspec',
            name='fuselage_width_ext',
        ),
        migrations.RemoveField(
            model_name='aircraftspec',
            name='height',
        ),
        migrations.RemoveField(
            model_name='aircraftspec',
            name='length',
        ),
        migrations.RemoveField(
            model_name='aircraftspec',
            name='maximum_fuel_capacity',
        ),
        migrations.RemoveField(
            model_name='aircraftspec',
            name='maximum_landing_weight',
        ),
        migrations.RemoveField(
            model_name='aircraftspec',
            name='maximum_operating_speed',
        ),
        migrations.RemoveField(
            model_name='aircraftspec',
            name='maximum_ramp_weight',
        ),
        migrations.RemoveField(
            model_name='aircraftspec',
            name='maximum_take_off_weight',
        ),
        migrations.RemoveField(
            model_name='aircraftspec',
            name='maximum_zero_fuel_weight',
        ),
        migrations.RemoveField(
            model_name='aircraftspec',
            name='replaces_current_model',
        ),
        migrations.RemoveField(
            model_name='aircraftspec',
            name='seating',
        ),
        migrations.RemoveField(
            model_name='aircraftspec',
            name='track',
        ),
        migrations.RemoveField(
            model_name='aircraftspec',
            name='wheelbase',
        ),
        migrations.RemoveField(
            model_name='aircraftspec',
            name='wing_span',
        ),
        migrations.AlterField(
            model_name='aircraftspec',
            name='range',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='range'),
        ),
    ]
