# Generated by Django 3.1.2 on 2020-11-02 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0013_auto_20201102_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraftspec',
            name='range',
        ),
    ]
