# Generated by Django 3.1.2 on 2020-11-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0014_remove_aircraftspec_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraftspec',
            name='range',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
    ]
