# Generated by Django 3.1.2 on 2020-11-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0015_aircraftspec_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraftspec',
            name='range',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
