# Generated by Django 3.1.2 on 2020-11-04 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0017_auto_20201102_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraftspec',
            name='type',
        ),
        migrations.DeleteModel(
            name='Aircraft',
        ),
        migrations.DeleteModel(
            name='AircraftSpec',
        ),
    ]
