# Generated by Django 3.1.2 on 2020-11-04 15:19

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aircraft', '0018_auto_20201104_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('family', models.CharField(max_length=30)),
                ('manufacture', models.CharField(choices=[('Airbus', 'Airbus'), ('Boeing', 'Boeing'), ('Lockheed Martin', 'Lockheed Martin')], max_length=55)),
                ('role', models.CharField(choices=[('NBRP', 'Narrow-body Regional jet airplane'), ('XWB', 'Extrawide-body jet airplane')], max_length=100)),
                ('slug', models.SlugField(blank=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('status', models.CharField(choices=[('LTD', 'Limited to freighters and executive use[a]'), ('INS', 'In service')], max_length=30)),
                ('featured_photo', models.ImageField(blank=True, upload_to='photos/airplanes/featured/%Y/%m/%d/')),
                ('photo1', models.ImageField(blank=True, upload_to='photos/airplanes/%Y/%m/%d/')),
                ('photo2', models.ImageField(blank=True, upload_to='photos/airplanes/%Y/%m/%d/')),
                ('photo3', models.ImageField(blank=True, upload_to='photos/airplanes/%Y/%m/%d/')),
                ('photo4', models.ImageField(blank=True, upload_to='photos/airplanes/%Y/%m/%d/')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('poststatus', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AircraftCapacity',
            fields=[
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='aircraft.aircraft')),
                ('seating', models.IntegerField(blank=True, null=True, verbose_name='Seating')),
                ('first_class', models.IntegerField(blank=True, null=True, verbose_name='First class')),
                ('business_class', models.IntegerField(blank=True, null=True, verbose_name='Business class')),
                ('economy_class', models.IntegerField(blank=True, null=True, verbose_name='Economy class')),
            ],
            options={
                'verbose_name': 'Aircraft Capacities',
            },
        ),
        migrations.CreateModel(
            name='AircraftDimensions',
            fields=[
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='aircraft.aircraft')),
                ('length', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Length')),
                ('wing_span', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Wing_span')),
                ('height', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Height')),
                ('fuselage_width_ext', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Fuselage width exterior')),
                ('cabin_width_Int', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Cabin width interior')),
                ('track', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Track')),
                ('wheelbase', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='wheelbase')),
            ],
            options={
                'verbose_name': 'Aircraft Dimensions',
            },
        ),
        migrations.CreateModel(
            name='AircraftEngines',
            fields=[
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='aircraft.aircraft')),
                ('title', models.CharField(max_length=55)),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='AircraftFreightCapacity',
            fields=[
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='aircraft.aircraft')),
                ('standard_uld_configuration', models.CharField(max_length=55)),
                ('forwardhold', models.CharField(max_length=55)),
                ('afthold', models.CharField(max_length=55)),
                ('cargo_volume', models.CharField(max_length=55)),
                ('Doorsizes', models.CharField(max_length=55)),
                ('cargo_pay_load', models.CharField(max_length=55)),
                ('maximum_permitted_heigh', models.CharField(max_length=55)),
            ],
            options={
                'verbose_name': 'Freught Capacities',
            },
        ),
        migrations.CreateModel(
            name='AircraftPerfomance',
            fields=[
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='aircraft.aircraft')),
                ('maximum_operating_speed', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Maximum operating speed')),
                ('maximum_ramp_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Maximum ramp weight')),
                ('maximum_take_off_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Maximum take off weight')),
                ('maximum_landing_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Maximum landing weight')),
                ('maximum_zero_fuel_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Maximum zero fuel weight')),
                ('maximum_fuel_capacity', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Maximum fuel capacity')),
            ],
            options={
                'verbose_name': 'Aircraft Perfomances',
            },
        ),
        migrations.CreateModel(
            name='AircraftSpec',
            fields=[
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='aircraft.aircraft')),
                ('range', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Range')),
                ('replaces_current_model', models.CharField(blank=True, max_length=30)),
                ('competes_against', models.CharField(blank=True, max_length=30)),
                ('engines', models.CharField(blank=True, choices=[('RRTrentXWB337kN (74,000 LBF)', 'RR Trent XWB 337kN (74,000 LBF)'), ('RRTrentXWB374kN (83,000 LBF)', 'RR Trent XWB 374kN (83,000 LBF)'), ('RRTrentXWB432kN (97,000 LBF)', 'RR Trent XWB 432kN (97,000 LBF)')], max_length=55)),
                ('average_unit_price', models.CharField(blank=True, max_length=15)),
            ],
            options={
                'verbose_name': 'Aircraft Specification',
            },
        ),
    ]
